INSERT into MILKPRODUCTS values('p01','milk',10,'200ml');
INSERT into MILKPRODUCTS values('p02','milk',20,'500ml');
INSERT into MILKPRODUCTS values('p03','curd',12,'200ml');
INSERT into MILKPRODUCTS values('p04','cure',20,'200gm');
INSERT into MILKPRODUCTS values('p05','milk',40,'1ltr');
INSERT into MILKPRODUCTS values('p06','curd',40,'1ltr');
INSERT into MILKPRODUCTS values('p07','lassi',12,'1ltr');
INSERT into MILKPRODUCTS values('p08','lassi',22,'2ltr');
INSERT into MILKPRODUCTS values('p09','icecream',10,'250gm');
INSERT into MILKPRODUCTS values('p10','icecream',20,'500gm');
INSERT into MILKPRODUCTS values('p11',' Nandini paneer',66,'200gm');
INSERT into MILKPRODUCTS values('p12','Nandini paneer',120,'400gm');
INSERT into MILKPRODUCTS values('p13','cheese',50,'250gm');
INSERT into MILKPRODUCTS values('p14','cheese',100,'500gm');
INSERT into MILKPRODUCTS values('p15','butter',210,'500gm');
INSERT into MILKPRODUCTS values('p16','cow ghee',200,'1kg');
INSERT into MILKPRODUCTS values('p17','white butter',350,'1kg');
INSERT into MILKPRODUCTS values('p18','kesar yoghurt',25,'80gm');
INSERT into MILKPRODUCTS values('p19','milk khova',180,'1kg'); 
INSERT into MILKPRODUCTS values('p20','milk shake',25,'180ml');
INSERT into MILKPRODUCTS values('p21','pure cow butter',540,'1kg'); 
INSERT into MILKPRODUCTS values('p22','raw milk yogurt',55,'1kg');
INSERT into MILKPRODUCTS values('p23','curd powder',285,'1kg');
INSERT into MILKPRODUCTS values('p24','white cream',350,'1kg');
INSERT into MILKPRODUCTS values('p25','fresh milk cream',210,'1kg');
INSERT into MILKPRODUCTS values('p26','curd powder',470,'1kg');
INSERT into MILKPRODUCTS values('p27','mozzarella cheese',450,'1kg');
INSERT into MILKPRODUCTS values('p28','chocolate milk',22,'180ml');
INSERT into MILKPRODUCTS values('p29','cold coffee milk',22,'180ml');
INSERT into MILKPRODUCTS values('p30','milk cake',180,'400gm');
INSERT into MILKPRODUCTS values('p31','hot gulab jamun',40,'2pc');
INSERT into MILKPRODUCTS values('p32','thanda rasogolla',40,'200gm');
INSERT into MILKPRODUCTS values('p33','kesar elaichi milk ',22,'180ml');
INSERT into MILKPRODUCTS values('p34','misti doi',180,'400gm');
INSERT into MILKPRODUCTS values('p35','Amul milk powder',134,'500gm');
INSERT into MILKPRODUCTS values('p36','Amul taaza toned milk',21,'500ml');
INSERT into MILKPRODUCTS values('p37','Amul lassi',15,'200ml');
INSERT into MILKPRODUCTS values('p38','Amul cheese slices',69,'100gm');
INSERT into MILKPRODUCTS values('p39','Amul kesar flavored milk',20,'200ml');
INSERT into MILKPRODUCTS values('p40','Amul elaichi shrikhand',95,'500gm');
INSERT into MILKPRODUCTS values('p41','Amul pure ghee(carton)',255,'500ml');
INSERT into MILKPRODUCTS values('p42','Amul cow ghee(pouch)',500,'1ltr');
INSERT into MILKPRODUCTS values('p43','Amul fresh cream',57,'200ml');
INSERT into MILKPRODUCTS values('p44','Amul butter',46,'100gm');
INSERT into MILKPRODUCTS values('p45','Amul butter(chiplets)',53,'150gm');
INSERT into MILKPRODUCTS values('p46','Amul lite low fat butter',155,'500gm');
INSERT into MILKPRODUCTS values('p47','Amul garlic & herbs butter',45,'100gm');
INSERT into MILKPRODUCTS values('p48','Amul cheese cubes',108,'200gm');
INSERT into MILKPRODUCTS values('p49','Amul rose favored milk',20,'200ml');
INSERT into MILKPRODUCTS values('p50','Amul masti curd',22,'200gm');
INSERT into MILKPRODUCTS values('p51','Amul koko chocolate flavored milk',30,'200ml');
INSERT into MILKPRODUCTS values('p52','Amul milk shake mango',25,'220gm');
INSERT into MILKPRODUCTS values('p53','Amul kool kesar',20,'200ml');
INSERT into MILKPRODUCTS values('p54','Amul ice cream-choco chips',175,'1ltr');
INSERT into MILKPRODUCTS values('p55','badam drink mix',96.03,'200gm');
INSERT into MILKPRODUCTS values('p56','calvins fruitshake,banana',30,'180ml');
INSERT into MILKPRODUCTS values('p57','Amul gula jamun',190,'1 pack');
INSERT into MILKPRODUCTS values('p58','Amul mithai mate',45,'200 gm');
INSERT into MILKPRODUCTS values('p59','Amul ice cream sugar free',30,'125ml');
INSERT into MILKPRODUCTS values('p60','Amul butterscotch',40,'1piece');
INSERT into MILKPRODUCTS values('p61','Amul american nuts ice cream',120,'750ml');
INSERT into MILKPRODUCTS values('p62','Amul rajbhog',199,'1ltr');
INSERT into MILKPRODUCTS values('p63','Amul roasted almond',199,'1ltr');
INSERT into MILKPRODUCTS values('p64','Amul choco chips ice cream',175,'1ltr');
INSERT into MILKPRODUCTS values('p65','Amul butterscotch bliss ice cream',135,'1ltr');
INSERT into MILKPRODUCTS values('p66','Amul vanilla magic ice cream',125,'1ltr');
INSERT into MILKPRODUCTS values('p67','Amul choco almond ice cream',80,'40');
INSERT into MILKPRODUCTS values('p68','Amul strawberry twist ice cream',40,'80ml');
INSERT into MILKPRODUCTS values('p69','Amul almond fudge ice cream',40,'125ml');
INSERT into MILKPRODUCTS values('p70','Amul chocolate fudge ice cream',40,'125ml');
INSERT into MILKPRODUCTS values('p71','Amul chocobar',10,'40ml');
INSERT into MILKPRODUCTS values('p72','Amul chocobar',15,'60ml');
INSERT into MILKPRODUCTS values('p73','Amul vanilla royale cup ice cream',10,'75ml');
INSERT into MILKPRODUCTS values('p74','Amul shrikhand badam pista',120,'1kg');
INSERT into MILKPRODUCTS values('p75','Amul shrikhand elachi',40,'200gm');
INSERT into MILKPRODUCTS values('p76','Amul shrikhand mango',95,'500gm');
INSERT into MILKPRODUCTS values('p77','milk rabdi',300,'1kg');
INSERT into MILKPRODUCTS values('p78','lachha rabdi',600,'1kg');
INSERT into MILKPRODUCTS values('p79','kesar shrikhand',400,'1kg');
INSERT into MILKPRODUCTS values('p80','shrikhand',360,'1kg');
INSERT into MILKPRODUCTS values('p81','Amul rasmalai',175,'500gm');
INSERT into MILKPRODUCTS values('p82','Amul basundi sweets',175,'1ltr');
INSERT into MILKPRODUCTS values('p83','Amul fresh cream',31,'500gm');
INSERT into MILKPRODUCTS values('p84','Amul kool milk',20,'200ml');
